### PR TITLE
chore: add .env support for development

### PR DESCRIPTION
**Pull request by thepolytheist**
# Issue
We'll want developers to have a file for settings env vars/secrets during development, but we never want this to be checked into source. By creating this file by default during setup, we can filter it out from Git and have a standard place to set these values.

# Changes
* Added .env creation to setup script
* Added .env to .gitignore

### CODE REVIEW

**Comment by thepolytheist** [comment]
@Merckinator Should we go ahead and add the `dotenv` gem while we're at it?

**Comment by Merckinator** [comment]
I wasn't sure; it's not needed to _use_ the gem, but it'd be handy for working _on_ it.

**Comment by thepolytheist** [comment]
Sure. I would imagine anyone actually consuming the gem would be passing in their secrets however they see fit, but for any contributors that would be helpful to add as a dev and test gem.

- [ ] Add dotenv gem for dev and test

**Comment by thepolytheist** [comment]
I didn't add a specific test group just yet, but it shouldn't be hard to split those dependencies out later if we want.

**Pull request merged**
